### ISSUE TITLE
Global overwrite of stdout and stderr

### ISSUE THREAD

**Issue by Anachron** [plytophogy/bashful#10]
It would be great to have the possibility to enable 2> && > redirection with a parameter for all execution commands. This allows to write all errors or output to a target file without needing to keep putting it in the command or function call. (something like execute_output or execute_error, without argument gets the current destination (defaults to stdout and stderr) and with sets the new target).

**Comment by plytophogy** [comment]
Closing this for now. I've been AFK for a long time. Reopen if this is still needed and we can talk more about it.
