### ISSUE TITLE
Simple example of how to use functions?

### ISSUE THREAD

**Issue by bradparks** [plytophogy/bashful#13]
Hey... Is there a wiki or blog post on this collection? I've got a bunch of small questions and wasn't sure where to ask them:
- Can these be used from zsh ? 
- So is the way to use these is to source them in a file? Or do I source them in my .bashrc or something like that?
- Also, do you know if there are similar collections of bash utils around, as I think this is an awesome idea, but this is the only collection of reusable bash scripts i've found....

Thanks!

**Comment by laughedelic** [comment]
Here's another similar library which I just encountered: https://github.com/jandob/rebash

**Comment by jmcantrell** [comment]
Thanks for the question. The readme definitely needs to be updated with some of this information.

1. They can, however it's not the most efficient way to use it. You can call any of the functions from another shell process like: `bashful-input choice a b c`

2. Ideally, you would source the needed scripts from your script. If they're in your PATH, then you can just add `source bashful-input` at the top of your script and all the exports from that are now available.

3. Likely, and looks like @laughedelic found one that looks interesting. When I was working on this project actively, I treated it as a place to store things that I found useful or tricky to get right in bash. If I was writing a script for personal use, I'd leave the includes in. If the plan was to publish it, I'd remove the includes and copy over the functions as needed from the modules.

I hope this helps, and I apologize for taking so long to respond.

**Comment by bradparks** [comment]
👍  thanks!
