### ISSUE TITLE
Unable to type on the script

### ISSUE THREAD

**Issue by srph** [plytophogy/bashful#3]
Good day!

I'm using Mac OSX, Yosemite, running this script via **Term2**. Is this an issue on my
 part that I am unable to type anything, even pressing `i` (I'm not good with `vi`, but `i` puts `vi` in insert mode). I am able to press keys, but it only activates the hotkeys (like `h` for `help`).

![bashful2](https://cloud.githubusercontent.com/assets/5093058/6705285/409629cc-cd8e-11e4-8966-f281c1f3f298.gif)

**Comment by first-developer** [comment]
It's working dude. The behaviour s like less not vim. This is made in this ligne : 
https://github.com/jmcantrell/bashful/blob/master/bin/bashful-doc#L75
