### ISSUE TITLE
Wrapper for RC != 0

### ISSUE THREAD

**Issue by Anachron** [plytophogy/bashful#9]
Sometimes it would be very handy to have a function like this:

``` shell
check_rc()
{
  if [[ $? -gt 0 ]]; then
    if [[ ${1} != "" ]]; then
      echo -e "${@}"
    fi
    exit 1
  fi
}
```

I've used it a couple of times now in my own coding, allowing critical actions to abort scripts very handy.

``` shell
startup_server 2> error.log
check_rc "Error: Could not start server, please check error.log!"
```

**Comment by jmcantrell** [comment]
That's a great idea!

**Comment by plytophogy** [comment]
Closing for now. Way out of date and the pull request needs lots of work.
